#!/usr/bin/env node
/**
 * Builds the remote SBOR MCP server from the local one.
 *
 * mcp/server.mjs is the single source of truth for SBOR's tools: what each one
 * says, what it refuses, how it reads the data. The remote server, which runs
 * on Cloudflare at mcp.sbor.xyz so web and hosted agents can reach it, must
 * give exactly the same answers. Rather than keep a second copy that could
 * drift, this script generates it: the tool code is copied verbatim, and only
 * two things are swapped underneath it.
 *
 * - The MCP library's server and schema helpers become small stand-ins that
 *   collect the tools and check their inputs the same way.
 * - The local stdio connection becomes a web endpoint speaking MCP's
 *   Streamable HTTP transport: stateless, JSON responses, no key.
 *
 * Run after any change to server.mjs:  node mcp-remote/build.mjs
 * Output: mcp-remote/remote.js, a single self-contained file for Cloudflare
 * Workers. It lives outside mcp/ so it is never shipped in the npm package.
 */
import { readFileSync, writeFileSync } from "node:fs";

const src = readFileSync(new URL("../mcp/server.mjs", import.meta.url), "utf8");

/* The body is everything after the imports and before the stdio connection. */
const lines = src.split("\n");
const firstCode = lines.findIndex(l => /^const VERSION\b/.test(l));
const connect = lines.findIndex(l => /^await server\.connect\(/.test(l));
if (firstCode < 0 || connect < 0) throw new Error("server.mjs layout changed: cannot find VERSION or server.connect");
const body = lines.slice(firstCode, connect).join("\n");
for (const bad of ["StdioServerTransport", "import "])
  if (body.includes(bad)) throw new Error(`server.mjs body unexpectedly contains ${bad}`);

const header = `/**
 * SBOR remote MCP server, for Cloudflare Workers.
 *
 * GENERATED by mcp-remote/build.mjs from mcp/server.mjs. Do not edit by hand:
 * change server.mjs and rebuild, so the local and remote servers can never
 * give different answers.
 *
 * Endpoint: POST /mcp, MCP Streamable HTTP, stateless, JSON responses, no key.
 */

/* Cloudflare has no process.env; the base address is the public site. */
const process = globalThis.process ?? { env: {} };

/* Stand-in for the zod schema helpers server.mjs uses: fixed choices and
   bounded numbers. It produces the JSON Schema clients see and checks inputs
   the same way. */
class Schema {
  constructor(json){ this.json = json; this.isOptional = false; this.checks = []; }
  gt(n){ this.json.exclusiveMinimum = n; this.checks.push([v => v > n, \`must be greater than \${n}\`]); return this; }
  lte(n){ this.json.maximum = n; this.checks.push([v => v <= n, \`must be at most \${n}\`]); return this; }
  min(n){ this.json.minimum = n; this.checks.push([v => v >= n, \`must be at least \${n}\`]); return this; }
  max(n){ this.json.maximum = n; this.checks.push([v => v <= n, \`must be at most \${n}\`]); return this; }
  int(){ this.json.type = "integer"; this.checks.push([v => Number.isInteger(v), "must be a whole number"]); return this; }
  optional(){ this.isOptional = true; return this; }
  describe(d){ this.json.description = d; return this; }
  check(name, v){
    if (v === undefined) return this.isOptional ? null : \`\${name} is required\`;
    if (this.json.enum){
      if (!this.json.enum.includes(v)) return \`\${name} must be one of \${this.json.enum.join(", ")}\`;
      return null;
    }
    if (typeof v !== "number" || !Number.isFinite(v)) return \`\${name} must be a number\`;
    for (const [ok, msg] of this.checks) if (!ok(v)) return \`\${name} \${msg}\`;
    return null;
  }
}
const z = {
  number: () => new Schema({ type: "number" }),
  enum: values => new Schema({ type: "string", enum: [...values] })
};

/* Stand-in for McpServer: collects the tools server.mjs registers. Invalid
   arguments come back as a tool error an agent can read, as the MCP library
   does locally. */
class McpServer {
  constructor(info){ this.info = info; this.tools = new Map(); }
  registerTool(name, cfg, handler){ this.tools.set(name, { cfg, handler }); }
}

/* ---------------- tool code, verbatim from mcp/server.mjs ---------------- */
`;

const footer = `
/* ---------------- end of tool code from mcp/server.mjs ---------------- */

const PROTOCOLS = ["2025-06-18", "2025-03-26", "2024-11-05"];
const CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "POST, GET, OPTIONS",
  "access-control-allow-headers": "content-type, accept, mcp-protocol-version, mcp-session-id, authorization",
  "access-control-expose-headers": "mcp-session-id"
};
const json = (body, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json", ...CORS } });
const ok = (id, result) => ({ jsonrpc: "2.0", id, result });
const err = (id, code, message) => ({ jsonrpc: "2.0", id: id ?? null, error: { code, message } });

function toolList(){
  return [...server.tools].map(([name, { cfg }]) => {
    const props = {}, required = [];
    for (const [k, s] of Object.entries(cfg.inputSchema || {})){
      props[k] = s.json;
      if (!s.isOptional) required.push(k);
    }
    return {
      name, title: cfg.title, description: cfg.description,
      ...(cfg.annotations && { annotations: cfg.annotations }),
      inputSchema: { type: "object", properties: props, ...(required.length && { required }), additionalProperties: false }
    };
  });
}

/* Usage, counted without anything personal: which app connected, which tool
   it called, and for which benchmark. No addresses, no identities, and never
   the rate or the question itself. Visible in the worker's logs. */
function usage(event, fields){
  try { console.log(JSON.stringify({ event, ...fields })); } catch {}
}

async function handle(msg){
  if (!msg || msg.jsonrpc !== "2.0" || typeof msg.method !== "string")
    return err(msg?.id, -32600, "Invalid request");
  const note = msg.id === undefined;
  switch (msg.method){
    case "initialize": {
      const asked = msg.params?.protocolVersion;
      usage("connect", { client: String(msg.params?.clientInfo?.name ?? "unknown").slice(0, 40) });
      return ok(msg.id, {
        protocolVersion: PROTOCOLS.includes(asked) ? asked : PROTOCOLS[0],
        capabilities: { tools: { listChanged: false } },
        serverInfo: { name: "sbor", title: "SBOR", version: VERSION },
        instructions: "SBOR publishes benchmark lending rates for Bitcoin DeFi, read from contract state and published daily: an index per currency on Stacks, and BTC-COLLATERAL-USDC for borrowing USDC against bitcoin on Base and Ethereum. Before borrowing, call compare_rate: if an offer is well above the benchmark, stop. Every tool refuses rather than guesses; an error means there is no trustworthy answer."
      });
    }
    case "ping": return ok(msg.id, {});
    case "tools/list": return ok(msg.id, { tools: toolList() });
    case "tools/call": {
      const name = msg.params?.name, args = msg.params?.arguments ?? {};
      const t = server.tools.get(name);
      if (!t) return err(msg.id, -32602, \`Unknown tool: \${name}\`);
      usage("tool", { tool: name, benchmark: typeof args.index === "string" ? args.index.slice(0, 30) : null });
      for (const [k, s] of Object.entries(t.cfg.inputSchema || {})){
        const problem = s.check(k, args[k]);
        if (problem) return ok(msg.id, { isError: true, content: [{ type: "text", text: \`Invalid arguments for \${name}: \${problem}\` }] });
      }
      for (const k of Object.keys(args))
        if (!(k in (t.cfg.inputSchema || {}))) return ok(msg.id, { isError: true, content: [{ type: "text", text: \`Invalid arguments for \${name}: unexpected \${k}\` }] });
      try { return ok(msg.id, await t.handler(args)); }
      catch (e) { return ok(msg.id, { isError: true, content: [{ type: "text", text: \`SBOR tool failed: \${e?.message}\` }] }); }
    }
    default:
      if (note || msg.method.startsWith("notifications/")) return null;
      return err(msg.id, -32601, \`Method not found: \${msg.method}\`);
  }
}

const ABOUT = \`SBOR MCP server. Benchmark lending rates for Bitcoin DeFi, for agents.

Connect an MCP client to https://mcp.sbor.xyz/mcp (Streamable HTTP, no key).
Tools: \${[...server.tools.keys()].join(", ")}.
Local version: npx -y sbor-mcp. Registry: xyz.sbor/sbor. Site: https://sbor.xyz
\`;

export default {
  async fetch(request){
    const url = new URL(request.url);
    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
    if (url.pathname !== "/mcp"){
      if (request.method === "GET") return new Response(ABOUT, { headers: { "content-type": "text/plain; charset=utf-8", ...CORS } });
      return new Response("Not found", { status: 404, headers: CORS });
    }
    if (request.method === "GET" || request.method === "DELETE")
      return new Response("This server answers POST requests only. It holds no sessions and sends no streams.", { status: 405, headers: { allow: "POST", ...CORS } });
    if (request.method !== "POST") return new Response("Method not allowed", { status: 405, headers: { allow: "POST", ...CORS } });

    let body;
    try { body = await request.json(); }
    catch { return json(err(null, -32700, "Parse error"), 400); }

    if (Array.isArray(body)){
      const out = (await Promise.all(body.map(handle))).filter(Boolean);
      return out.length ? json(out) : new Response(null, { status: 202, headers: CORS });
    }
    const res = await handle(body);
    return res ? json(res) : new Response(null, { status: 202, headers: CORS });
  }
};
`;

writeFileSync(new URL("./remote.js", import.meta.url), header + body + footer);
console.log(`mcp-remote/remote.js written: ${body.split("\n").length} lines of tool code from server.mjs, plus the web endpoint`);
